# fly.toml app configuration file generated for yjs-demos on 2023-11-21T21:32:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yjs-demos"
primary_region = "ams"
swap_size_mb = 0

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 1000
    soft_limit = 800

[[services]]
  protocol = ""
  internal_port = 0
  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200
